## This script is used to concatenate get_charge_from_Bobs_script_gmn_all_tg.csv with beamCh_n_daqLvTM_prun_Target.csv files

In [1]:
import pandas as pd

### Step 1: Reading charge generated using Bob's script

In [2]:
# Read sheet with Bob's charge numbers
bobch = pd.read_csv('get_charge_from_Bobs_script_gmn_all_tg.csv')
bobch.head()

   runnum  totcharge_bob(C)
0   11436         -0.000101
1   11500         -0.000068
2   11547         -0.000085
3   11548         -0.000485
4   11573        -99.000000

In [3]:
# check for nulls
anyNaN_bob = bobch.isnull().values.any()
#final_table_nz_nd.loc[pd.isna(final_table_nz_nd).any(1), :].index
#if (anyNaN == True): 
#    print('NaN exists! Replacing with 0')
#    concatdfch = concatdfch.fillna(0)
print(anyNaN_bob)

False

### Step 2: Reading beamcharge and daq LT generated by my scripts

In [25]:
# Define the appropriate input variables
sbsconfch = [4, 7, 11, 14, 8, 9]
targetch = 'LD2'
replay_pass = 2
outfilech = '{}/all_beamCh_n_daqLvTm_prun_{}.csv'.format(targetch,targetch)

In [26]:
# Create a list with all relevant files to be concatenated
prefixch  = '{}/beamCh_n_daqLvTm_prun_SBS'.format(targetch)
sheetsch = []    # list to store dfs per config 
for conf in sbsconfch:
    filename = prefixch + str(conf) + '_' + targetch + '.csv'
    tempdf = pd.DataFrame(pd.read_csv(filename))
    sheetsch.append(tempdf)

In [27]:
# concatenate tables from all different sbs configs
concatdfch = pd.concat(sheetsch)
print(concatdfch.head())
print(concatdfch.shape)

   runnum  totcharge_pd(C)  daqlvtm_bbhi  daqlvtm_ts1
0   11449         0.002906      0.930779     0.930785
1   11451         0.002176      0.861596     0.861605
2   11452         0.008985      0.936185     0.936191
3   11456         0.007570      0.886523     0.886531
4   11493         0.002369      0.976892     0.976899
(568, 4)

In [28]:
# check for nulls
anyNaN = concatdfch.isnull().values.any()
#final_table_nz_nd.loc[pd.isna(final_table_nz_nd).any(1), :].index
#if (anyNaN == True): 
#    print('NaN exists! Replacing with 0')
#    concatdfch = concatdfch.fillna(0)
print(anyNaN)

False

### Step 3: Concatenate the two

In [29]:
# Finally merge the new tables with good run list
bob_n_pd = pd.merge(bobch, concatdfch, on='runnum', how='inner')
bob_n_pd

     runnum  totcharge_bob(C)  totcharge_pd(C)  daqlvtm_bbhi  daqlvtm_ts1
0     11449         -0.000439         0.002906      0.930779     0.930785
1     11451         -0.000055         0.002176      0.861596     0.861605
2     11452        -99.000000         0.008985      0.936185     0.936191
3     11456        -99.000000         0.007570      0.886523     0.886531
4     11493         -0.000088         0.002369      0.976892     0.976899
..      ...               ...              ...           ...          ...
563   13779          0.087621         0.078559      0.949878     0.949881
564   13793          0.026766         0.024007      0.951103     0.951107
565   13797          0.050772         0.045499      0.952950     0.952953
566   13798          0.042783         0.038330      0.963683     0.963687
567   13799          0.039753         0.035655      0.956673     0.956677

[568 rows x 5 columns]

In [30]:
# check for nulls
anyNaN_tot = bob_n_pd.isnull().values.any()
#final_table_nz_nd.loc[pd.isna(final_table_nz_nd).any(1), :].index
#if (anyNaN == True): 
#    print('NaN exists! Replacing with 0')
#    concatdfch = concatdfch.fillna(0)
print(anyNaN_tot)

False

### CAUTION!!
<span style="color:red">Execute the cells below only when super confident!</span>

In [31]:
bob_n_pd.to_csv(outfilech, index=False)